### ISSUE TITLE
Запуск в текущей директории

### ISSUE THREAD

**Issue by murych** [sergey27564/YeahBoyRep#1]
Строка
```bash
FILES=$(find ~ -name $1)
```
ищет файлы по маске в директории `$HOME`, что занимает __очень__ много времени и вообще не нужно. Скрипт должен искать файлы в папке, в которой он запущен, или добавить новый флаг для запуска `-d` `--dir` для указания папки для поиска файлов вручную

**Comment by sergey27564** [comment]
Решил в ветке dev
